# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import load_balancer_pb2 as load__balancer__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in load_balancer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LoadBalancerStub(object):
    """Smart Load Balancer Service v3.0
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterClient = channel.unary_unary(
                '/loadbalancer.LoadBalancer/RegisterClient',
                request_serializer=load__balancer__pb2.ClientInfo.SerializeToString,
                response_deserializer=load__balancer__pb2.RegistrationResponse.FromString,
                _registered_method=True)
        self.ProcessAIRequest = channel.unary_unary(
                '/loadbalancer.LoadBalancer/ProcessAIRequest',
                request_serializer=load__balancer__pb2.AIRequest.SerializeToString,
                response_deserializer=load__balancer__pb2.AIResponse.FromString,
                _registered_method=True)
        self.GetProcessingStatus = channel.unary_unary(
                '/loadbalancer.LoadBalancer/GetProcessingStatus',
                request_serializer=load__balancer__pb2.StatusRequest.SerializeToString,
                response_deserializer=load__balancer__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/loadbalancer.LoadBalancer/HealthCheck',
                request_serializer=load__balancer__pb2.Empty.SerializeToString,
                response_deserializer=load__balancer__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.GetAvailableModels = channel.unary_unary(
                '/loadbalancer.LoadBalancer/GetAvailableModels',
                request_serializer=load__balancer__pb2.Empty.SerializeToString,
                response_deserializer=load__balancer__pb2.AvailableModelsResponse.FromString,
                _registered_method=True)
        self.ReassignModels = channel.unary_unary(
                '/loadbalancer.LoadBalancer/ReassignModels',
                request_serializer=load__balancer__pb2.Empty.SerializeToString,
                response_deserializer=load__balancer__pb2.ReassignmentResponse.FromString,
                _registered_method=True)
        self.AddDocument = channel.unary_unary(
                '/loadbalancer.LoadBalancer/AddDocument',
                request_serializer=load__balancer__pb2.AddDocumentRequest.SerializeToString,
                response_deserializer=load__balancer__pb2.AddDocumentResponse.FromString,
                _registered_method=True)
        self.SearchDocuments = channel.unary_unary(
                '/loadbalancer.LoadBalancer/SearchDocuments',
                request_serializer=load__balancer__pb2.SearchDocumentsRequest.SerializeToString,
                response_deserializer=load__balancer__pb2.SearchDocumentsResponse.FromString,
                _registered_method=True)
        self.CreateChatSession = channel.unary_unary(
                '/loadbalancer.LoadBalancer/CreateChatSession',
                request_serializer=load__balancer__pb2.CreateChatSessionRequest.SerializeToString,
                response_deserializer=load__balancer__pb2.CreateChatSessionResponse.FromString,
                _registered_method=True)
        self.GetChatSessions = channel.unary_unary(
                '/loadbalancer.LoadBalancer/GetChatSessions',
                request_serializer=load__balancer__pb2.GetChatSessionsRequest.SerializeToString,
                response_deserializer=load__balancer__pb2.GetChatSessionsResponse.FromString,
                _registered_method=True)
        self.GetChatHistory = channel.unary_unary(
                '/loadbalancer.LoadBalancer/GetChatHistory',
                request_serializer=load__balancer__pb2.GetChatHistoryRequest.SerializeToString,
                response_deserializer=load__balancer__pb2.GetChatHistoryResponse.FromString,
                _registered_method=True)


class LoadBalancerServicer(object):
    """Smart Load Balancer Service v3.0
    """

    def RegisterClient(self, request, context):
        """Client registration with smart model assignment
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessAIRequest(self, request, context):
        """Process AI request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProcessingStatus(self, request, context):
        """Get processing status (for progress tracking)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableModels(self, request, context):
        """Get available models (for client verification)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReassignModels(self, request, context):
        """Reassign models (for dynamic rebalancing)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddDocument(self, request, context):
        """RAG operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateChatSession(self, request, context):
        """Chat history operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChatSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChatHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LoadBalancerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterClient': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterClient,
                    request_deserializer=load__balancer__pb2.ClientInfo.FromString,
                    response_serializer=load__balancer__pb2.RegistrationResponse.SerializeToString,
            ),
            'ProcessAIRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessAIRequest,
                    request_deserializer=load__balancer__pb2.AIRequest.FromString,
                    response_serializer=load__balancer__pb2.AIResponse.SerializeToString,
            ),
            'GetProcessingStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProcessingStatus,
                    request_deserializer=load__balancer__pb2.StatusRequest.FromString,
                    response_serializer=load__balancer__pb2.StatusResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=load__balancer__pb2.Empty.FromString,
                    response_serializer=load__balancer__pb2.HealthResponse.SerializeToString,
            ),
            'GetAvailableModels': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableModels,
                    request_deserializer=load__balancer__pb2.Empty.FromString,
                    response_serializer=load__balancer__pb2.AvailableModelsResponse.SerializeToString,
            ),
            'ReassignModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ReassignModels,
                    request_deserializer=load__balancer__pb2.Empty.FromString,
                    response_serializer=load__balancer__pb2.ReassignmentResponse.SerializeToString,
            ),
            'AddDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.AddDocument,
                    request_deserializer=load__balancer__pb2.AddDocumentRequest.FromString,
                    response_serializer=load__balancer__pb2.AddDocumentResponse.SerializeToString,
            ),
            'SearchDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchDocuments,
                    request_deserializer=load__balancer__pb2.SearchDocumentsRequest.FromString,
                    response_serializer=load__balancer__pb2.SearchDocumentsResponse.SerializeToString,
            ),
            'CreateChatSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateChatSession,
                    request_deserializer=load__balancer__pb2.CreateChatSessionRequest.FromString,
                    response_serializer=load__balancer__pb2.CreateChatSessionResponse.SerializeToString,
            ),
            'GetChatSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChatSessions,
                    request_deserializer=load__balancer__pb2.GetChatSessionsRequest.FromString,
                    response_serializer=load__balancer__pb2.GetChatSessionsResponse.SerializeToString,
            ),
            'GetChatHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChatHistory,
                    request_deserializer=load__balancer__pb2.GetChatHistoryRequest.FromString,
                    response_serializer=load__balancer__pb2.GetChatHistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loadbalancer.LoadBalancer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('loadbalancer.LoadBalancer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LoadBalancer(object):
    """Smart Load Balancer Service v3.0
    """

    @staticmethod
    def RegisterClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loadbalancer.LoadBalancer/RegisterClient',
            load__balancer__pb2.ClientInfo.SerializeToString,
            load__balancer__pb2.RegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessAIRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loadbalancer.LoadBalancer/ProcessAIRequest',
            load__balancer__pb2.AIRequest.SerializeToString,
            load__balancer__pb2.AIResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProcessingStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loadbalancer.LoadBalancer/GetProcessingStatus',
            load__balancer__pb2.StatusRequest.SerializeToString,
            load__balancer__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loadbalancer.LoadBalancer/HealthCheck',
            load__balancer__pb2.Empty.SerializeToString,
            load__balancer__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAvailableModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loadbalancer.LoadBalancer/GetAvailableModels',
            load__balancer__pb2.Empty.SerializeToString,
            load__balancer__pb2.AvailableModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReassignModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loadbalancer.LoadBalancer/ReassignModels',
            load__balancer__pb2.Empty.SerializeToString,
            load__balancer__pb2.ReassignmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loadbalancer.LoadBalancer/AddDocument',
            load__balancer__pb2.AddDocumentRequest.SerializeToString,
            load__balancer__pb2.AddDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loadbalancer.LoadBalancer/SearchDocuments',
            load__balancer__pb2.SearchDocumentsRequest.SerializeToString,
            load__balancer__pb2.SearchDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateChatSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loadbalancer.LoadBalancer/CreateChatSession',
            load__balancer__pb2.CreateChatSessionRequest.SerializeToString,
            load__balancer__pb2.CreateChatSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChatSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loadbalancer.LoadBalancer/GetChatSessions',
            load__balancer__pb2.GetChatSessionsRequest.SerializeToString,
            load__balancer__pb2.GetChatSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChatHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loadbalancer.LoadBalancer/GetChatHistory',
            load__balancer__pb2.GetChatHistoryRequest.SerializeToString,
            load__balancer__pb2.GetChatHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
